services:
  app:
    image: 441356678868.dkr.ecr.ap-south-1.amazonaws.com/electricity-billing:${IMAGE_TAG}
    ports:
      - "8081:8081"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: electricity_billing
      DB_USER: root
      DB_PASSWORD: ${DB_PASSWORD}	
    depends_on: 
      mysql:
        condition: service_healthy


  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: electricity_billing
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uroot", "-p${DB_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 10


volumes:
  mysql-data: